### PR TITLE
Straightforward generalization for alternate text representations

### PR DESCRIPTION
**Pull request by ddssff**
This patch adds a Chars class, which has several operations from the ListLike class.  It updates all the code so that instead of the String type any instance of Chars can be used.  A Text.PrettyPrint.String module is added which specializes the public API for the String type.  This module is re-exported by Text.PrettyPrint.

In order to avoid new dependencies, no instance for Text is included in library, but the instance is provided in the tests directory.  For the same reason, the ListLike class is not used.

It may be that older versions of GHC will not accept the new extensions required to compile these changes.

Hopefully this patch will be useful at some point.  Let me know if it needs revision.

### CODE REVIEW

**Comment by ddssff** [comment]
Closing this while I fix up the travis build.

**Comment by ddssff** [comment]
I'm removing the `Chars` class for now because it is just a bad version of `ListLike`.   While I realize that `pretty` is bundled with `ghc` and therefore needs to have a minimum of new dependencies (like, none), I'm going to add `ListLike` and text for the time being.  I feel good about adding text, because String is an abomination.  I'm also adding modules `Text.PrettyPrint.TextStrict`, `Text.PrettyPrint.TextLazy`, and annotated versions as well.  I'm less thrilled about adding the `ListLike` dependency, but it is easy enough to back out or split up going forward.  And maybe there won't be any interest in this patch anyway, so why worry?

**Comment by dterei** [comment]
Wow! Thanks for all the hard work.

I'm not sure if we want to abstract the base storage type though. I nearly did something like this myself once before, but after talking with others at GHCHQ we decided that there was a good use-case for the extra abstraction.

Why? Because you can control the output type by using `fullRender` and providing your own conversion function of type `TextDetails -> a -> a`.

I think adding support for `ByteString` and `Text` to `TextDetails` makes sense, but abstracting is a lot of complexity and type-class leakage than seems valuable. Adding `Text` will require talking to GHCHQ first though since `pretty` is included by default and `text` isn't.

**Comment by ddssff** [comment]
I'm not sure the fullRender trick solves the enormous space and time inefficiency of using the String type as the base storage type.  This pull request is mostly an attempt to find out how badly using String affects the space requirement of programs that use packages like haskell-src-exts, haskell-src-meta, haxml, htf and haskell-names.

**Comment by dterei** [comment]
Sure. I could see `String` being a problem. The question is, does adding a `ByteString` constructor to `TextDetails` solve this? That is a far simpler solution than abstracting away the storage type with a type-class.

**Comment by ddssff** [comment]
Ah.

**Comment by dterei** [comment]
@ddssff Going to go ahead and close this for now, but really value the contribution and hard work, so please feel free to reopen / try the approach I suggested.

**Comment by ddssff** [comment]
I have actually discovered that for a lot of uses it is surprisingly difficult to achieve the performance of String using Text or ByteString.

**Pull request closed without merging**
